parameters:
#    site_front.example.class: Site\FrontBundle\Example

services:
#    site_front.example:
#        class: %site_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
