parameters:
#    liwei_admin.example.class: Liwei\AdminBundle\Example

services:
#    liwei_admin.example:
#        class: %liwei_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
